"""empty message

Revision ID: 33752f6e1e5e
Revises: 
Create Date: 2023-02-16 01:31:51.451913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33752f6e1e5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('ADDITION', 'SUBSTRACTION', 'MULTIPLICATION', 'DIVISION', 'SQUARE_ROOT', 'RANDOM_STRING', name='operationtypes'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
